### ISSUE TITLE
No blocks tab in page view on SS 3.5.3

### ISSUE THREAD

**Issue by SiWhite** [sheadawson/silverstripe-blocks#117]
Hi there, I've installed the latest version of silverstripe-blocks via composer on a fresh install of SS 3.5.3 but I am not seeing the blocks tab in the page view. 

I do see the 'Blocks Model Admin' section in the dashboard, and can create a block fine there, but the functionality is missing from the pages. I have read through your readme a couple of times, and not sure if I've missed something. I have flushed after updating yml and template files. Any advice would be appreciated - thanks.

mysite/_config/config.yml:

```
BlockManager:
  areas:
    MyBlockArea: true

```
... / Layout/Page.ss:

```
<article>
 <h1>$Title</h1>
  $BlockArea(MyBlockArea)
 <div class="content">$Content</div>
</article>
```

**Comment by sheadawson** [comment]
The config is changed in the master branch for the SS4 release. See config in readme for the version you are using, which requires configuration per theme https://github.com/sheadawson/silverstripe-blocks/tree/1.1.1

**Comment by SiWhite** [comment]
Thanks a lot, appreciate the response. Is there a specific version I should use for SS 3.5.3?

**Comment by sheadawson** [comment]
Use the latest stable release. That's 1.1.1. If you install via composer with prefer-stable set to true in your composer.json config that's what you'll get.

**Comment by SiWhite** [comment]
Thanks a lot!
