### ISSUE TITLE
Make blocks sortable by drag & drop on a per page basis (OrderableGridfield)

### ISSUE THREAD

**Issue by micschk** [sheadawson/silverstripe-blocks#12]
I think it makes sense to allow sorting blocks on a per page basis (within a BlockArea). Stretching this further, I think it's also worth considering if the BlockArea shouldn't also be on a many_many_extrafields field instead of the Block itself, to allow placement of the block on a per page basis as well (but that may be less of an issue).

I'm currently working on an implementation where I have drag & drop sorting working (quick hack status) by basing the sort on a many_many_extraFields on the Page-Blocks relation and drag & drop via OrderableGridfield. But would like to consult you on if you generally think this is a viable idea, and as well on how you'd think we can combine this with the 'blocks inherited from SiteConfig' and 'blocks from BlockSets'.

One possible direction would be to use a dropdown on Blocks in a Blockset and SiteConfig (again many_many_extrafields), to allow picking a position 'above' or 'below' page-specific blocks instead of weight. This would sacrifice a bit of the control on site-wide blocks in exchange for more fine-grained control on page-specific blocks. And exceptions can always be made by blocking inherited blocks on a page and re-adding them on a specific position. Would this work for your current implementations as well or do you have different use cases?

**Comment by sheadawson** [comment]
Nice work! Just been going through it all now and have pushed up some more changes. Most notably:

* Removed global blocks (block sets can be used to achieve the same thing)
* Added ability to exclude any page types from using blocks
* Dropped support for multisites module
* Tidied up block sets
* Block ExtraCSSClasses is now an optional feature (enabled via yaml config)
* Use AddNewMulticlass for adding new blocks in gridfield

Notes:

* You added GridFieldDetailFormCustom class (used in model admin) but it's not in the repo. Do we still need this?
* Wondering how we would best allow the user to select block area in the same step as creating a block from site tree/block gridfield? At the moment it's a 3 step process to create a block from page edit view, could be two steps?
* PageListAsString - This is really nice. Would be great to list block sets that the block is applied to too
* I think I'm happy not to add legacy support for all these changes. Do you think it's worth it?

Keen to hear any of your thoughts on where we're up to now. Thanks for your work :)

**Comment by sheadawson** [comment]
Ok I've just completed the most part of the stuff we set out to do and released a 1.0 branch. See the readme for full list of new features. And thanks for your help!
