### ISSUE TITLE
Add existing relies on $Title

### ISSUE THREAD

**Issue by arambalakjian** [sheadawson/silverstripe-blocks#14]
Great work on the module Shea, a very useful addition to SS.

I have noticed that the "Add Existing" search window relies on $Title being present, otherwise it just shows a list of empty rows.

I understand the reason for removing the $Title field and replacing it with $Name, but it then makes it quite messy to have to add $Title to every subclass of Block and explain to CMS editors what the difference is. For now I am adding a getTitle() function to return $Name, but I imagine there is a better way to deal with this from within the module.

Unfortunately it doesn't look like the GridFieldAddExistingSearchButton allows you to specify the Label field which would have been the most obvious solution. 

Aram

**Comment by arambalakjian** [comment]
I've just realised this is a little more complex when you actually want to use $Title as a front-end field. If $Name is meant for CMS use and the $Title is meant for front end, then the GridFieldAddExistingSearchButton needs to use $Name rather than $Title.

Currently you would have to do the following:
```
		$fields->addFieldToTab('Root.Main', new TextField('Title', 'Name (CMS Use Only)'),'BlockArea');
		$fields->addFieldToTab('Root.Main', new TextField('Name', 'Title'),'BlockArea');
```

And then use $Name in the front end as though it were $Title...

Pretty horrible :)

**Comment by arambalakjian** [comment]
Also related to this is that the CMS breadcrumbs do not display the name of the block you are currently on, as they also rely on a $Title field too.

In all honesty, I'm not convinced that the semantic benefits of removing Block::$Title outweigh the complications and issues that it causes elsewhere.

As I understand it all DataObjects should have a $Title field anyway, whether it's used on the front-end or not, otherwise you start getting into issues where it's assumed to exist.

**Comment by micschk** [comment]
Hi Aram, Shea,

I'm the one responsible for changing the Title to Name, with the reasoning
as described. I haven't noticed the necessity for a Title field because I
added a fallback getTitle while developing, like you did. For obvious
reasons this didn't make it into the merged version.

However, I'd vote against just adding back the title field, as it's a wrong
assumption that all blocks necessarily need a title. For
GridFieldAddExistingSearchButton, we'd better make a Fix/PR adding
functionality to pick the searchfield to that module. As for the
breadcrumbs, we'd have to look into that as well, as DataObjects shouldn't
to my opinion be required to have a Title by default. If they are, that's
something to fix in the framework instead of building on onto a wrong
assumption.

**Comment by sheadawson** [comment]
Thanks for you input on this guys. I was really on the fence with the idea of adding the Name field or not, there's good arguments on both sides. 

With my use of Blocks I've always just had Title for use in both front and backend and that has been fine. And now upgrading my projects to use Blocks 1.0 I am ending up just using the Name field as the Title field in the frontend and backend (I have no need for a second field here). 

There is a getTitle method on DataObject that falls back to Name but it's obviously not getting used in all cases. 

I'm going to agree with Aram here, we're creating more issues than it's worth and I'm happy to revert back to using Title. If anyone needs a separate field for frontend they can add a Heading field. 

Will push the changes up shortly

**Comment by sheadawson** [comment]
Reverted in https://github.com/sheadawson/silverstripe-blocks/commit/684d675063bf06e02631188effb78ca266e666d2

**Comment by arambalakjian** [comment]
Great thanks guys, I agree arguments on both sides but until the other bits become more flexible it seems like the best bet.
