### ISSUE TITLE
Templates includes folder should start with captal i

### ISSUE THREAD

**Issue by giovdk21** [sheadawson/silverstripe-blocks#15]
Hello,
I'm new with SilverStripe but it seems that the folder "blocks/templates/includes" should instead be called 
"blocks/templates/Includes" to be compatible to the default structure of the template and therefore allow template files to be overridden.

(This is a problem only on case sensitive file systems)

Thanks.

**Comment by sheadawson** [comment]
Hey, thanks for letting me know :)

Fixed in https://github.com/sheadawson/silverstripe-blocks/commit/e443c269ed9e2e737c33c26fb28c5fbaede96de8
