### ISSUE TITLE
SS 3.7.2 / PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by Xarinor** [sheadawson/silverstripe-blocks#156]
1. Replace in blocks/code/BlockManager.php `class BlockManager extends Object` to `class BlockManager extends SS_Object`
2. Require `silverstripe-australia/gridfieldextensions ^2.0` instead of `silverstripe-australia/gridfieldextensions ~1.0`
3. Change default sort in blocks/code/dataobjects/Block.php: Can't use Title as of now for new MySQL Versions.

**Comment by xini** [comment]
This has been fixed in #157.
