### ISSUE TITLE
Remove the need to edit template files

### ISSUE THREAD

**Issue by phptek** [sheadawson/silverstripe-blocks#17]
I've only used the module a short time (I was developing something similar - but this is way better in most departments) but one thing that immediately struck me was that I needed to physically edit template files to add the block locations.

I've added some incomplete mods (but if you pull the code you'll see where I'm headed) that remove the need to do this and instead rely on the user in the CMS ordering arbitrary named blocks. These are passed onto SSViewer which then pushes them to the template's default `$Content` placeholder, with the actual Content and any additional blocks above or below it.

At the moment it's a simply Textfield in the settings area. But that of course means the same "configuration" everywhere. This could easily be changed to be done on a page by page basis, just porting the logic off the SiteConfig `DataExtension` onto a `Page` DataExtension. If I get time, I'll finish it off, this was about ~5h work on company hackday a couple of weeks ago.

See the "master-russ" branch on my fork and let me know if I'm on or completely off track with it :-)

**Comment by sheadawson** [comment]
Hi,

I think I can see where this is going but I'm not sure it's a direction I want to go in. I've done my best to keep this module as simple as possible, and I'd prefer to only add additional layers of complexity (code or cms ui) if it's really worth it. In this case, it only takes a couple of seconds to add the $BlockArea call in template files, so I don't see this as an issue at all. Also, in my experience BeforeContent and AfterContent areas are not used on all websites. And having $BlockArea(Whatever) in templates makes it clear what's going on and easy to work into any markup in the main template files.

Please let me know if I've missed something here but, at this stage I would prefer not to add this feature. Thanks for your proposed change and efforts all the same.
