### ISSUE TITLE
Wrapping base ContentBlock in config use_default_blocks doesn't undefine it

### ISSUE THREAD

**Issue by micschk** [sheadawson/silverstripe-blocks#19]
This method doesn't allow creation of a replacement ContentBlock class (class already defined).
This method also causes a 'Uncaught ReflectionException: Class ContentBlock does not exist' error.

Suggestion would be to remove the ContentBlock class definition altogether and place it in the README as an example.

**Comment by sheadawson** [comment]
Thanks, I've been aware of this for a while actually but needed a reminder :)
