### ISSUE TITLE
BlockManager::getTheme() ignoring theme from SiteConfig ?

### ISSUE THREAD

**Issue by derRobert** [sheadawson/silverstripe-blocks#31]
Hi should the getTheme() method look, if there is a theme defined in SiteConfig?
In my case the SSViewer.theme is empty, so it always falls back to default although there is a theme defined in SIteConfig.

Proposal:

```
    private function getTheme(){
        $currentTheme = Config::inst()->get('SSViewer', 'theme');
		if( class_exists('SiteConfig') ) { // supporting cms-less installations
			if ($siteconfigTheme = SiteConfig::current_site_config()->Theme ) {
				$currentTheme = $siteconfigTheme;
			}
		}
        return $currentTheme ? $currentTheme : 'default';
    }
```

**Comment by sheadawson** [comment]
Thanks for that. ContentController::init() sets SSViewer.theme from SiteConfig but this issue would occur if getTheme was called before ContentController::init() had run.

**Comment by mikeyc7m** [comment]
yeah um this doesn't work. the proposal code as suggested by derRobert should be used.
