### ISSUE TITLE
SilverStripe 3.2 compatibility

### ISSUE THREAD

**Issue by jeffwhitfield** [sheadawson/silverstripe-blocks#32]
With v3.2.0-rc1, a final version of SilverStripe v3.2 is eminent. So...any chance we can get this addon updated to allow for installation on v3.2.x?  :)

**Comment by sheadawson** [comment]
Hi Jeff. I won't have time to do it until October as I'm flat out on projects at the moment. Community contributions welcome!

**Comment by sheadawson** [comment]
I haven't looked into 3.2 yet.. have you got a feel for how much work is involved in updating this module?

**Comment by jeffwhitfield** [comment]
No worries. I know how it is. On a big project myself. Will see if I can get it updated and contribute it as a pull request.  :D

**Comment by jeffwhitfield** [comment]
Not yet. Just installed the module manually for testing. Will know more by the end of the week. Once I’ve figured it out, will add it in as a pull request. Gut feeling says it shouldn’t require much to get it working. Probably just a few tweaks to how some of the existing methods are used.

**Comment by sheadawson** [comment]
Ok cool, yeah hopefully it's just minor and we can have one version that
runs across 3.1 and 3.2. Thanks in advance for any PRs :)

On Thu, Aug 27, 2015 at 10:02 AM, Jeff Whitfield <notifications@github.com>
wrote:

> Not yet. Just installed the module manually for testing. Will know more by
> the end of the week. Once I’ve figured it out, will add it in as a pull
> request. Gut feeling says it shouldn’t require much to get it working.
> Probably just a few tweaks to how some of the existing methods are used.
>
>
> > On Aug 26, 2015, at 5:01 PM, Shea Dawson <notifications@github.com>
> wrote:
> >
> > I haven't looked into 3.2 yet.. have you got a feel for how much work is
> involved in updating this module?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/sheadawson/silverstripe-blocks/issues/32#issuecomment-135184519
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/32#issuecomment-135185501>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by jeffwhitfield** [comment]
An initial dev/build of the module went well. No errors. We'll see how the rest of the module goes.

**Comment by jacobsjensen** [comment]
@jeffwhitfield did you hit any errors with the module this far?

**Comment by jeffwhitfield** [comment]
I'll test this sometime tomorrow. I've got a small demo project I've been meaning to put together. Good opportunity to test this out.  :)

**Comment by anselmdk** [comment]
Seems this can be closed now - see #44
