### ISSUE TITLE
Applying a blockset to a tree node _doesn't_ apply it to that node itself

### ISSUE THREAD

**Issue by nyeholt** [sheadawson/silverstripe-blocks#34]
I can't remember if this was a specific design decision or not, but - if I apply a blockset to a particular node, the children of that node have that blockset applied to it, but the selected node itself doesn't. Is there another way to do this - ie apply a blockset to a node and all its children (instead of just the children?). The logic change is straightforward

```
$ancestors = $this->owner->getAncestors()->column('ID');		
// add ourselves to the lookup tree
$ancestors[] = $this->owner->ID;
```

but I'm not sure if this is intended functionality or not

**Comment by sheadawson** [comment]
Yeah it's the intended functionality. Can we retain it and add the option to apply the set to the parent nodes too, with a checkbox?

**Comment by nyeholt** [comment]
Yep that was my plan, I'll pr something :)
