### ISSUE TITLE
init() doesn't work on Block_Controller and subclasses

### ISSUE THREAD

**Issue by sekjal** [sheadawson/silverstripe-blocks#38]
Goal: to be able to load in custom Requirements (JS and CSS) on a per-Block basis.  With Widgets, this was accomplished by adding an init() function to the WidgetController.  This method does not carry through to Blocks.

This may be related:  when attempting to access {$URLSegment}/block/{$Block-ID}, a 500 error is generated with message:
```
Call to a member function getController() on a non-object in /var/www/blocks/code/extensions/BlockContentControllerExtension.php on line 32
```
Such an error does not occur with Widgets, which have a similar ContentController extension.

**Comment by sheadawson** [comment]
Hi Sekjal, you can place your requirements calls in your template. I think that's the best approach as it keeps frontend stuff in the frontend. Alternatively you can place them in the forTemplate() method on your Block class. 

The controller error might be an issue specific to 3.2. I think we need to give the controller a url segment. You on ss 3.2?

**Comment by sekjal** [comment]
Still running 3.1.13.  Once I get through this next major dev push, I'll look at upgrading.

I'll add the Requirements to the templates temporarily, but I've just made a move system-wide to put them all in the controllers.  If I can figure out how to get init() to work more or less normally, would that be a worthwhile pull request?

**Comment by sheadawson** [comment]
What do we gain from being able to use a controller init() method over a
forTemplate() on the model? Is it just consistency with the way it's often
done on pages/contentcontrollers? Might be worth while but not a biggie.
Happy to merge a PR if you send one through.

On Thu, Dec 3, 2015 at 9:53 AM, Ian Walls <notifications@github.com> wrote:

> Still running 3.1.13. Once I get through this next major dev push, I'll
> look at upgrading.
>
> I'll add the Requirements to the templates temporarily, but I've just made
> a move system-wide to put them all in the controllers. If I can figure out
> how to get init() to work more or less normally, would that be a worthwhile
> pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/38#issuecomment-161430862>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by sekjal** [comment]
Point taken; using forTemplate() does exactly what I'd want init() to do, so why prioritize this over other enhancements?  Perhaps a note in the documentation on how to do this would be a better pull request... I'll work on that and submit.

**Comment by sheadawson** [comment]
Sure thing :)

On Fri, Dec 4, 2015 at 3:06 AM, Ian Walls <notifications@github.com> wrote:

> Point taken; using forTemplate() does exactly what I'd want init() to do,
> so why prioritize this over other enhancements? Perhaps a note in the
> documentation on how to do this would be a better pull request... I'll work
> on that and submit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/38#issuecomment-161649515>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz
