### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by thezenmonkey** [sheadawson/silverstripe-blocks#57]
Just wondering how to enable Shortcode parsing in Content Blocks using Shortcodeable module

**Comment by sheadawson** [comment]
Assuming you have both modules installed: If you have a block with an HTMLText db field and WYSIWYG editor form field, a shortcode button will appear on the WYSIWYG editor toolbar.

If you'd like Block objects to be Shortcodable (embed blocks inside HTMLEditorField contents), you'll need to add the Shortcodable interface to your Block subclasses ie. ```class MyBlock extends Block implements Shortcodable``` See readme at https://github.com/sheadawson/silverstripe-shortcodable for details on that.
