### ISSUE TITLE
Integrating Site Search

### ISSUE THREAD

**Issue by thezenmonkey** [sheadawson/silverstripe-blocks#63]
Any tips on integrating content blocks in site search? Maybe I jumped the gun by instaaling Searchable DataObjects since it just gives links to the blocks in the page instead of the page.

**Comment by sheadawson** [comment]
Hmm... You could hook into the onAfterPublish method on your Page model,
and inside that loop over any blocks applied to that page, copy/save the
content of the blocks to a searchable field on your Page. You'd probably
need to put a bit of thought into the best way to do this as you'd also
need to update the search content field when blocks are added, removed or
edited on a page

On Thu, Feb 18, 2016 at 3:47 PM, Richard Rudy <notifications@github.com>
wrote:

> Any tips on integrating content blocks in site search? Maybe I jumped the
> gun by instaaling Searchable DataObjects since it just gives links to the
> blocks in the page instead of the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/63>.
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz
