### ISSUE TITLE
Dynamic blocks

### ISSUE THREAD

**Issue by robbieaverill** [sheadawson/silverstripe-blocks#64]
Hi @sheadawson 

Please let me know if this is the wrong way to ask, but I wonder whether you have thought about making the position/number of blocks dynamic rather than having "Sidebar", "Before Content" and "After Content".

For example, it may be useful to have any number of blocks (already doable) and have them be part of the actual page content rather than not shown in the WYSIWYG editor at all, and let them be reordered as the content editor requires.

Your thoughts.

Thanks,
Robbie

**Comment by sheadawson** [comment]
Hi Robbie. There are no restrictions around number of blocks or what areas they should be placed in. It sounds like you read the example config in the README file as being hard coded. Rather, it's just an example of one of the ways you could configure the module for a website.

This module can be used as a replacement for WYSIWYG content. But this one is designed more specifically for that https://github.com/dnadesign/silverstripe-elemental

**Comment by robbieaverill** [comment]
Hey @sheadawson 

Great - thanks for the quick reply.

Cheers,
Robbie
