### ISSUE TITLE
Current page context?

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-blocks#69]
Hey Shea,

Is it possible to get the current page from inside a Block template and how do you do that?

**Comment by jonom** [comment]
So you could do $Page.Title for instance.

**Comment by jonom** [comment]
Looks like I can add this to `Block` to get what I want - do you want a PR to add this to the Block class? Might be useful for many.
```php
public function CurrentPage()
{
    return Director::get_current_page();
}
```

**Comment by sheadawson** [comment]
Nice one Jono, yeah sure let's add it. Not sure if CurrentPage() or just
Page() ?

On Wed, Mar 9, 2016 at 12:47 PM, Jono Menz <notifications@github.com> wrote:

> Looks like I can add this to Block to get what I want - do you want a PR
> to add this to the Block class? Might be useful for many.
>
> public function CurrentPage(){    return Director::get_current_page();}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/69#issuecomment-194027834>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by jonom** [comment]
I'm guessing Page could be common for a relationship name so might lead to confusion? CurrentPage seems less likely to cause a conflict.

**Comment by sheadawson** [comment]
Good point, agreed :)

On Wed, Mar 9, 2016 at 1:28 PM, Jono Menz <notifications@github.com> wrote:

> I'm guessing Page could be common for a relationship name so might lead to
> confusion? CurrentPage seems less likely to cause a conflict.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-blocks/issues/69#issuecomment-194035660>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by jonom** [comment]
Forked this module on github and got so confused trying to make changes... somehow I got an old version of it!
![screen shot 2016-03-09 at 8 56 07 am](https://cloud.githubusercontent.com/assets/1079425/13643275/e48c8238-e5d4-11e5-925b-26c0841f2fe9.png)
Oh.... I must have forked this before. :facepalm: I wish github had said "You already have a fork of this" :)
