### ISSUE TITLE
Can't click grid rows

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-blocks#72]
I notice you can't click anywhere on a grid row to edit a block like you can with most other grid fields, and wondered if that is deliberate or maybe a side effect of having form controls within the rows? I can't seem to re-train my brain to click the edit button instead of the row so would be cool if we could make the row clickable :)

**Comment by jonom** [comment]
If we can't make the rows clickable I think we should remove the hover effect and pointer cursor which implies you can click the rows.

**Comment by micschk** [comment]
I think this behaviour comes from gridfieldextensions editablecolumns,
probably should be fixed there.
Op 11 mrt. 2016 17:55 schreef "Jono Menz" <notifications@github.com>:

**Comment by sheadawson** [comment]
Yes this is an issue with gridfieldextensions editablecolumns. closing here :)

**Comment by jonom** [comment]
Cheers, have opened an issue there: https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/135
