### ISSUE TITLE
Feature Idea: 'internal' title

### ISSUE THREAD

**Issue by sekjal** [sheadawson/silverstripe-blocks#96]
For some kinds of Blocks, it makes sense to have a single, mostly-unique title.  This makes it easy to search for the specific Block in the CMS, and provides a descriptor to the end user.

Some Blocks, however, don't need a title for the end-user, as they may be making use of an external API or using some kind of rich media.  Other Blocks would benefit from having a title that's contextually descriptive ("Contact Me!" or "Open Hours"), but not necessarily unique to that Block.  Both these cases make it hard to find an existing Block to include it, as the Title is either blank or non-unique.

Proposal:  split Title into two, like it is for SiteTree (Title and MenuTitle).  One Title is meant for internal use (how you'd describe it in the CMS so you can find it easily) while the other is for showing on the front-end (optional).  A similar default behavior to SiteTree could be set up to keep things simple for Block creators who don't need this differentiation.

**Comment by sheadawson** [comment]
So some blocks need no title, some need one title, and some need two different titles. I'm don't think I want to try to support all three cases "out of the box", unless there is a good reason to add that. But I do feel it would be good to make it easy for developers to have the flexibility where they need it.

Currently we have 1 title field by default - Title.

If a developer doesn't want a title field on their blocks, they can remove it globally with a data extension or on a per-block-type basis in their Block subclasses.

If a developer want an additional title field for use in the frontend ie. Heading, they can add that globally via a data extension or on a per-block-type basis in their subclasses.

I feel the module allows the flexibility for all three cases to be implemented pretty easily but of course, I'm open to any suggestions you might have to improve it.

**Comment by micschk** [comment]
Just a quick note; the current Title is needed for
the GridFieldAddExistingSearchButton.
I usually treat the default Title as 'block description' in order to find
back the block later.

You can find an example of this here;
https://github.com/micschk/silverstripe-block_enhancements/blob/master/code/forms/GFConf_BlockManagerEnhanced.php#L51

**Comment by sheadawson** [comment]
Good point @micschk. Closing for now, if there are any issues or limitations with the current set up feel free to comment
