### ISSUE TITLE
Translatable Compatabilty

### ISSUE THREAD

**Issue by thezenmonkey** [sheadawson/silverstripe-blocks#97]
Just wondering if you have any guidance on implementing silverstripe translatable for the module?

**Comment by sheadawson** [comment]
I have zero experience with translatable, sorry! Let us know how you go

**Comment by thezenmonkey** [comment]
Here's a quick working GIST to support basic translatable fucntionality. It will create translated versions of blocks when translatlating a page

https://gist.github.com/thezenmonkey/6e6730023af553f12e3ab762ace3b08a

**Comment by sheadawson** [comment]
Thanks for that, I've added a note and link to your gist in the readme :)

**Comment by hohl** [comment]
How do you apply the posted `TranslatableBlockPage`?

**Comment by thezenmonkey** [comment]
You need to add the Translatable extension to the Block. Once thats done either add the onTranslatableCreate() from the gist to your Page class or apply the DataExtension to your SiteTree. The reason it's seperate is because you may need modify the onTranslatableCreate() depending on your specfic requirements.

**Comment by hohl** [comment]
For me that crashes at

**Comment by hohl** [comment]
For me that crashes at

```$block = $originalBlock->createTranslation($translatedPage->Locale);```

Telling me that `ERROR [User Error]: Uncaught Exception: Object->__call(): the method 'createtranslation' does not exist on 'ImageOnlyBlock'`. (`ImageOnlyBlock` is one of my custom blocks.)

Any ideas what I'm doing wrong? I'm using Silverstripe 3.3 and the most recent version of the silverstripe-blocks and silverstripe-translate plugin.

**Comment by thezenmonkey** [comment]
You also need to add the translatable extension to both the page and the block

**Comment by hohl** [comment]
Thank you, that's all I need. I just added `Block::add_extension('Translatable');` and now it works.

**Comment by hohl** [comment]
While with that configuration every seems to work, it's still not possible to create new blocks and add it to another language then the default language. 

For my case: At first all pages where created in the primary language `de_CH` and then I used the  `Create Translation` button to translate all of them to `en_US`. Everything seem to work back then. Now I tried to create a new block on an `en_US` page and when I saved the block I didn't get any error message, but the block didn't appear in the front nor in the backend. So I looked up the block in the backend and found that it has the locale field set to `de_CH` even if it was attach to an `en_US` page. Once I manually changed the locale to the correct one, the block got displayed.

Can anybody give me an hint about how to write a DataExtension which fixes that newly created blocks get assigned the correct locale?

**Comment by hohl** [comment]
No ideas? I would just need to know where to hack in to correctly set the `locale` field on the newly created block. Isn't there a way to catch "new block created" event using a `DataExtension`?

**Comment by thezenmonkey** [comment]
Current Locale should be assigned via the Translatable extension by default whenever you create a new translatable dataobject.

**Comment by hohl** [comment]
Thank you.

However, all I found yet, was that the form for creating a new block already contains the wrong locale. (So the POST request for creating the block sends always the primary language.)
